### ISSUE TITLE
Read only associations still show check boxes

### ISSUE THREAD

**Issue by marshallworster** [mendix/CheckboxSetSelector#1]
Previous versions had a Read-Only attribute that I was hoping I could get back but more importantly; If I’m logged in as a user with read rights to the association for the set selector I am presented with clickable check boxes on the page. Thankfully the associations are not getting set and the console blows up with a permissions error

**Comment by MxPvdK** [comment]
I wasn't aware this issue was open on Github when I pushed my changes; The latest commit fixes this issue
