### ISSUE TITLE
Header not translatable

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/CheckboxSetSelector#5]
Hi,

Seeing that you fix issues with such high speed, I will push my luck with another issue :) 

The `Header text` property of the `Display attributes` collection is not translatable; when I switch the Modeler's edit language to French, the `Header text` preserves the same value it had in English.

Thanks!

**Comment by Rvthof** [comment]
Fixed and I updated the release with the new version.
Beware that the new version will reset all values for Header in the widget, as sadly the Modeler doesn't keep the existing values when you go from String to TranslatableString.
