### ISSUE TITLE
No Constructor Found Error on CheckBox Set Selector in 6.5

### ISSUE THREAD

**Issue by jcsalazar** [mendix/CheckboxSetSelector#8]
Upgraded to 6.5 and getting "Could not create widget CheckboxSelector.widget.checkboxselector: TypeError: Clas is not a constructor" on the CheckBox Set Selector Widget.

Any ideas on how I can fix this?

**Comment by JelteMX** [comment]
That is weird. I have tested the widget here with 6.5.0 and there seem to be no errors. Two things:
- Check if you have the latest version of the widget, download it in the AppStore
- Clean your deployment folder and redeploy again.
Does the problem still persist then?

**Comment by Rvthof** [comment]
Could be cache?

**Comment by JelteMX** [comment]
Could be cache indeed. @jcsalazar what you can try is opening your chrome inspector (assuming you work on Chrome), open the Network tab and check "Disable cache". Now, while keeping the inspector open, refresh the page

![screen shot 2016-05-26 at 15 31 41](https://cloud.githubusercontent.com/assets/14937393/15576198/084c0c24-2357-11e6-86ad-888070df10f7.png)

**Comment by jcsalazar** [comment]
Thank you! Clearing my cache and deployment folder Worked!
